addCommandAlias("ci-test", "scalafmtCheck; scalafmtSbtCheck; test")
addCommandAlias("ci-docs", "github; project-docs/mdoc; headerCreateAll")

lazy val exercises = (project in file("."))
  .enablePlugins(ExerciseCompilerPlugin)
  .settings(exercisesSettings)

lazy val `project-docs` = (project in file(".docs"))
  .aggregate(exercises)
  .dependsOn(exercises)
  .settings(moduleName := "exercises-project-docs")
  .settings(mdocIn := file(".docs"))
  .settings(mdocOut := file("."))
  .settings(skip in publish := true)
  .enablePlugins(MdocPlugin)
