resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("com.47deg"           % "sbt-org-policies" % "0.13.3")
addSbtPlugin("org.scala-exercises" % "sbt-exercise"     % "0.6.0-SNAPSHOT")
addSbtPlugin("com.geirsson"        % "sbt-ci-release"   % "1.5.3")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"         % "2.1.5")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"     % "2.3.3")
addSbtPlugin("com.alejandrohdezma" % "sbt-mdoc-toc"     % "0.2")
